# Generated by Django 4.2 on 2023-04-24 13:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('DataMorte', models.DateField(blank=True, null=True, verbose_name='Morto')),
            ],
            options={
                'ordering': ['nome', 'sobrenome'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='digite um genero de livro', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sumario', models.TextField(help_text='digite uma breve descrição do livro', max_length=1000)),
                ('isbn', models.CharField(help_text='13 caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.autor')),
                ('genero', models.ManyToManyField(help_text='selecione o(s) genero(s) do livro', to='catalogos.genero')),
            ],
        ),
        migrations.CreateModel(
            name='LivroFisico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID exclusivo para este livro específico.', primary_key=True, serialize=False)),
                ('imprimir', models.CharField(max_length=200)),
                ('dataDevolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Manutenção'), ('o', 'Emprestado'), ('a', 'Disponivel'), ('r', 'Reservado')], default='m', help_text='Disponibilidade do livro:', max_length=1)),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.livro')),
            ],
            options={
                'ordering': ['dataDevolucao'],
            },
        ),
        migrations.CreateModel(
            name='meuModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meuCampo', models.CharField(help_text='digite meuCampo', max_length=20)),
            ],
            options={
                'ordering': ['-meuCampo'],
            },
        ),
        migrations.DeleteModel(
            name='MyModelName',
        ),
    ]
