# Generated by Django 4.2 on 2023-04-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_idioma_livro_idioma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='DataMorte',
            new_name='dataMorte',
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Titulo do livro'),
        ),
    ]
