# Generated by Django 4.2 on 2023-05-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_livrofisico_mutuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrofisico',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Manutenção'), ('e', 'Emprestado'), ('d', 'Disponivel'), ('r', 'Reservado')], default='m', help_text='Disponibilidade do livro:', max_length=1),
        ),
    ]
