# Generated by Django 4.2 on 2023-05-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0013_alter_autor_datamorte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='meuModelo',
        ),
    ]
