# Generated by Django 4.2 on 2023-05-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0014_delete_meumodelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='dataMorte',
            field=models.DateField(blank=True, null=True, verbose_name='morte'),
        ),
    ]
